### ISSUE TITLE
enrollment error (Agent version missing)

### ISSUE THREAD

**Issue by jmpolvera** [flyve-mdm/android-mdm-agent#542] opened 2018-08-18 03:20 UTC
Agent version missing error message trying to enroll new device.

**To Reproduce**
1. download and install apk
2. open the app and accept permissions
3. Fill out: first name, last name and email
4. See attached error log file
[log3_len.txt](https://github.com/flyve-mdm/android-mdm-agent/files/2299102/log3_len.txt)

**Smartphone (please complete the following information):**
 - Device: Lenovo YT3-X50F
 - OS: Android 6.0.1
 Flyve-mdm-android agent 2.0.0-rc.2 (https://github.com/flyve-mdm/android-mdm-agent/releases/tag/2.0.0-rc.2)

**Comment by jdavidthomson** [comment] 2018-08-18 21:02
Here are some logs related to this issue.  I'm not sure what the problem is but I downloaded the develop branch of the agent source and build.  So, have tried both 2.0 apks and the rebuild after the commit late last night.

Problem exists after filling out the user information screen and trying to enroll.

Environment
Docker Envvironment for Flyve MDM Platform
Latest develop branch of MDM Android Agent
Nexus 7 tablet with custom rom of Lineage OS; includes google apps


`08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: │ Thread: Thread-11
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: │ ConnectionHTTP.getSyncWebData  (ConnectionHTTP.java:105)
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: │    FlyveLog.d  (FlyveLog.java:60)
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: │ URL: http://192.168.1.86/glpi/apirest.php/PluginFlyvemdmAgent
08-18 17:00:09.370 26252 27308 D org.flyve.mdm.agent: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-18 17:00:09.376 26252 26263 I art     : Background partial concurrent mark sweep GC freed 11722(3MB) AllocSpace objects, 44(3MB) LOS objects, 39% free, 7MB/11MB, paused 946us total 141.693ms
08-18 17:00:10.014 26252 27308 E org.flyve.mdm.agent: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-18 17:00:10.015 26252 27308 E org.flyve.mdm.agent: │ Thread: Thread-11
08-18 17:00:10.015 26252 27308 E org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:10.017 26252 27308 E org.flyve.mdm.agent: │ EnrollmentHelper$2.run  (EnrollmentHelper.java:219)
08-18 17:00:10.017 26252 27308 E org.flyve.mdm.agent: │    FlyveLog.e  (FlyveLog.java:118)
08-18 17:00:10.017 26252 27308 E org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:10.017 26252 27308 E org.flyve.mdm.agent: │ ["ERROR_GLPI_ADD","Enrollment failed"]
08-18 17:00:10.017 26252 27308 E org.flyve.mdm.agent: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-18 17:00:10.024 26252 27308 E org.flyve.mdm.agent: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
08-18 17:00:10.027 26252 27308 E org.flyve.mdm.agent: │ Thread: Thread-11
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: │ EnrollmentHelper$2.run  (EnrollmentHelper.java:223)
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: │    FlyveLog.e  (FlyveLog.java:118)
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: │ Enrollment failed - Device serial: 07949eab
08-18 17:00:10.028 26252 27308 E org.flyve.mdm.agent: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────`

**Comment by jdavidthomson** [comment] 2018-08-18 22:13
This is the error on the tablet in adb logcat.
["ERROR_GLPI_ADD","Agent version missing"]

**Comment by rafaelje** [comment] 2018-08-21 14:05
Hello @jdavidthomson please review with our RC.3 https://github.com/flyve-mdm/android-mdm-agent/releases/tag/2.0.0-rc.3 you can download the apk from here:

https://github.com/flyve-mdm/android-mdm-agent/releases/download/2.0.0-rc.3/MDMAgent-2.0.0-rc.3.apk

**Comment by btry** [comment] 2018-08-21 21:16
@farfou confirmed this version works. Waiting for feedback from @jdavidthomson before closing.

**Comment by btry** [comment] 2018-08-22 05:26
Great, I close then.

**Closed by btry** 2018-08-22 05:26 UTC
Labels: bug

**Comment by jdavidthomson** [comment] 2018-08-22 08:58
yup.  i think it's fine.  In my test build i did basically the same thing and it worked.  I got communication with my server.  The thing is my server is messed up now so I can't test your build atm. If i encounter issues I will msg.
