### ISSUE TITLE
MDMAgent Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by jfreakazoid** [flyve-mdm/android-mdm-agent#535] opened 2018-08-02 15:28 UTC
**Describe the bug**
Once you try to enroll a new device, is not possible due to the following error message: MDMAgent Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**To Reproduce**
1. Go to 'MDMAgent'
2. Scan 'the QR code'
3. Enroll 'the device'

**Expected behavior**
To sent the inventory and enroll the device as expected. 

**Screenshots**
![img-20180730-wa0016](https://user-images.githubusercontent.com/10604088/43420103-7925aab2-9408-11e8-8c83-4dba42bcfc43.jpg).

**Smartphone (please complete the following information):**
 - Device: [Huawei MYA-L03]
 - OS: [Android Marshmellow 6.0]

**Additional information:**
- Using MDMAgent version 2.0.1-beta.1995

**Comment by rafaelje** [comment] 2018-08-17 15:31
Hello @jfreakazoid we launch today a new version please try it and give us a review and please let me know if you are trying with our demo site or your own instance of Flyve MDM

**Comment by spinaldf** [comment] 2018-08-21 12:39
Hi, I have same problem. I use 2.0.0-rc.1.2001. I use my instance of Flyve MDM
My android is version 5.0.2

![photo_2018-08-21_09-37-38](https://user-images.githubusercontent.com/42477982/44401680-c60e5080-a525-11e8-858a-ce0c03724a4b.jpg)

**Comment by rafaelje** [comment] 2018-08-21 14:27
Hello @jfreakazoid I'm working to show a better message here to understand the problem, by the way we have a new RC 3 https://github.com/flyve-mdm/android-mdm-agent/releases/tag/2.0.0-rc.3

**Comment by rafaelje** [comment] 2018-08-22 21:11
@jfreakazoid we made a new release on beta channel please try with this version, it has a better detail on the error message to know exactly where come from:

https://play.google.com/apps/testing/org.flyve.mdm.agent

**Comment by rafaelje** [comment] 2018-08-24 15:54
I cannot reproduce this error with the new version, I'll close it but feel free to reopen if is required

**Closed by rafaelje** 2018-08-24 15:54 UTC
Labels: bug

**Comment by jfreakazoid** [comment] 2018-08-30 15:57
@rafaelje Thank you very much. Let me test and I'll let you know. Best regards,

**Comment by doudz** [comment] 2019-06-03 10:12
I'm facing the same problem.
I'm trying to use the release 2.0 rc7 from github on Android 9

**Comment by tacanakase** [comment] 2020-01-22 13:55
Hello everybody :)   
I'm try install rc7 (2.0) with no success. And 7/ 7.1/ 8.0 - and Flyve plugin on GLPI 
I'm get erorr: `Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject `
Device: Huawei MediaPad T5 ,   
@rafaelje , do U can send me access to beta version (beta channel)? :D , maybe I get some...

**Comment by stonebuzz** [comment] 2020-01-22 16:08
Hi @tacanakase the message indicate that GLPI return STRING message rather than JSON ,
i think you have an http error (ie 500 or 404) 
can you check log on server (GLPI logs and web server logs)

I you want you can build by yourself the develop branch, 
a lot of improvements have been made

Best regards

**Comment by tacanakase** [comment] 2020-01-23 11:34
Hi @stonebuzz, thx for resp, Normally GLPI server communicates correctly with the mobile devices. We checked all addresses, ports and operation of http servers. Everything looks ok. With Flyve MDM still we get errors. In ver. rc6 get this: [Wrong information, data: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">] when try REQUEST PERMISSION, and next we get JSON error. In ver. rc7 only JSON.  
Actually we try last version from Teclib on And ver. 7.1 and 8.0

Regards

**Comment by stonebuzz** [comment] 2020-01-23 11:39
Are you using FCM version or MQTT ?

Best regards

**Comment by tacanakase** [comment] 2020-01-23 11:41
Both :D

**Comment by tacanakase** [comment] 2020-01-23 11:42
Actually MQTT

Regards

**Comment by stonebuzz** [comment] 2020-01-23 11:45
If you use MQTT check logs on MQTT server side, 
 
at what step have you this error -> Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**Comment by tacanakase** [comment] 2020-01-23 11:57
- Check logs on GLPI side where I install Flyve plugin?  
- I have this error after entering user information and click checkbox on top of app. I can click red DISMISS and again click checkbox, and again get error. I stuck :)

**Comment by stonebuzz** [comment] 2020-01-23 12:07
Try restart All enrollment process from scratch by cleaninf agent / invitation

**Comment by stonebuzz** [comment] 2020-01-23 12:09
And active explicit debug mode on flyvemdm plugin To Get more infos
