### ISSUE TITLE
Enrollment error with JSON object

### ISSUE THREAD

**Issue by spinaldf** [flyve-mdm/android-mdm-agent#553] opened 2018-08-23 13:02 UTC
What data do I need to add?

I can't add my User information, show this error.

`Value[] of type org.json.JSONArray cannot be converted to JSONObject`

![screenshot_2018-08-23-09-48-52](https://user-images.githubusercontent.com/42477982/44526784-71044300-a6bb-11e8-8332-5bc7bf935311.png)

Show this error on Sql log.

![error](https://user-images.githubusercontent.com/42477982/44530863-c6455200-a6c5-11e8-9ed2-ab9a5c7b9fd5.png)

**Comment by rafaelje** [comment] 2018-08-23 16:11
I cannot reproduce this error but add a new classification error to show exactly where come from the problem

**Comment by rafaelje** [comment] 2018-08-24 14:03
@spinaldf did you try the new version? or could I close this issue?

**Comment by rafaelje** [comment] 2018-08-24 16:48
This is the new screen with the code error:

![987215db-8d3b-402e-bed5-84fc952fb45f](https://user-images.githubusercontent.com/4085091/44596935-feb75f80-a79b-11e8-9ac1-6485e479ed00.png)

**Comment by spinaldf** [comment] 2018-08-30 20:52
This problem solved when I removed "redirect parameter" of apache.

#RewriteEngine On
#Redirect 302 / http://Mydomain.com/

**Closed** 2018-08-31 19:04 UTC
Labels: bug
